# Generated by Django 5.2.17 on 2026-08-18 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_autor_livro_autores'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('editora', models.CharField(max_length=100)),
                ('numero_edicao', models.IntegerField(default=1)),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='catalogo.livro')),
            ],
        ),
    ]
